import { CharacterData } from "@/lib/types";

const now = () => new Date().toISOString();

export const createSeedCharacter = (): CharacterData => ({
  id: "brek-field-kit",
  core: {
    name: "Brek",
    className: "Artificer",
    subclass: "Alchemist",
    level: 7,
    species: "Goblin",
    background: "Failed Merchant",
    alignment: "Chaotic Good",
  },
  abilities: {
    Strength: { score: 8, modifier: -1 },
    Dexterity: { score: 15, modifier: 2 },
    Constitution: { score: 14, modifier: 2 },
    Intelligence: { score: 16, modifier: 3 },
    Wisdom: { score: 12, modifier: 1 },
    Charisma: { score: 10, modifier: 0 },
  },
  stats: {
    ac: 15,
    maxHp: 47,
    currentHp: 47,
    tempHp: 0,
    speed: "30 ft.",
    initiative: "+2",
    spellSaveDc: 14,
    spellAttackBonus: "+6",
    intelligenceModifier: "+3",
    proficiencyBonus: "+3",
    darkvision: "60 ft.",
    languages: ["Common", "Dwarvish", "Undercommon"],
  },
  resources: [
    { id: "slot1", name: "Level 1 spell slots", current: 4, max: 4, resetType: "long-rest" },
    { id: "slot2", name: "Level 2 spell slots", current: 3, max: 3, resetType: "long-rest" },
    { id: "flash", name: "Flash of Genius", current: 3, max: 3, resetType: "long-rest", notes: "Reaction, +3" },
    { id: "lucky", name: "Lucky", current: 3, max: 3, resetType: "long-rest" },
    { id: "fury", name: "Fury of the Small", current: 3, max: 3, resetType: "long-rest", notes: "Once per turn vs larger creature" },
    { id: "elixirs", name: "Experimental Elixirs", current: 4, max: 4, resetType: "long-rest", notes: "Track current total vials" },
    { id: "ring", name: "Spell-Refueling Ring", current: 1, max: 1, resetType: "dawn", notes: "If active" },
    { id: "shield", name: "Repulsion Shield charges", current: 4, max: 4, resetType: "dawn", notes: "If active" },
    { id: "veech-hp", name: "Veech HP", current: 11, max: 11, resetType: "manual" },
  ],
  reminders: [
    { id: "savant", title: "Alchemical Savant", summary: "When Brek casts with alchemist's supplies as the focus, add +3 to one healing roll or one acid, fire, necrotic, or poison damage roll.", pinned: true },
    { id: "flash-r", title: "Flash of Genius", summary: "When Brek or an ally within 30 feet makes an ability check or saving throw, Brek can use a reaction to add +3.", pinned: true },
    { id: "lucky-r", title: "Lucky", summary: "Before the outcome is known, spend a point to roll another d20 and choose which die counts.", pinned: true },
    { id: "fury-r", title: "Fury of the Small", summary: "When damaging a creature larger than Brek, add +3 damage once per turn.", pinned: true },
    { id: "tools", title: "Tool Expertise", summary: "Double proficiency bonus on proficient tool checks, for a +6 proficiency contribution before ability mods.", pinned: true },
    { id: "nimble", title: "Nimble Escape", summary: "Bonus action Hide or Disengage.", pinned: true },
    { id: "veech-default", title: "Veech", summary: "Defaults to Dodge unless Brek spends a bonus action to command another action.", pinned: true },
  ],
  decisionPrompts: {
    beforeActing: [
      "What is the biggest problem right now?",
      "Would a spell, elixir, item, or Veech solve it better than attacking?",
      "Do I need my bonus action for Hide, Disengage, Healing Word, or Veech?",
      "Do I need to preserve my reaction for Flash of Genius, Lucky, or a reaction spell?",
      "Is the target larger than Brek, allowing Fury of the Small?",
    ],
    whenRollHappens: [
      "Ability check or saving throw: Flash of Genius? Lucky? Guidance? Tool Expertise?",
      "Damage roll: Alchemical Savant? Fury of the Small?",
      "Ally is down: Healing Word?",
      "Touch spell needed at range: Can Veech deliver it?",
    ],
    expanded: true,
  },
  attacks: [
    { id: "blood-spear", name: "Blood Spear", attackBonus: "+4", damage: "1d6+1", damageType: "piercing", range: "20/60", traits: ["thrown", "versatile", "sap"] },
    { id: "crossbow", name: "Light Crossbow", attackBonus: "+5", damage: "1d8+2", damageType: "piercing", range: "80/320", traits: ["ammunition", "loading", "two-handed", "slow"] },
    { id: "dagger", name: "Dagger", attackBonus: "+5", damage: "1d4+2", damageType: "piercing", range: "20/60", traits: ["finesse", "light", "thrown", "nick"] },
    { id: "dart", name: "Dart", attackBonus: "+5", damage: "1d4+2", damageType: "piercing", range: "20/60", traits: ["finesse", "thrown", "vex"] },
  ],
  spells: [
    { id: "guidance", name: "Guidance", level: 0, prepared: true, alwaysPrepared: true, actionType: "action", range: "Touch", concentration: true, saveOrAttack: "Utility", summary: "Add 1d4 to one ability check.", tags: ["utility", "support", "cantrip"] },
    { id: "mending", name: "Mending", level: 0, prepared: true, alwaysPrepared: true, actionType: "action", range: "Touch", concentration: false, saveOrAttack: "Utility", summary: "Repairs a break or tear in an object.", tags: ["utility", "cantrip"] },
    { id: "healing-word", name: "Healing Word", level: 1, prepared: true, alwaysPrepared: true, actionType: "bonus", range: "60 ft.", concentration: false, saveOrAttack: "Healing", summary: "Emergency ranged healing for a downed ally.", tags: ["healing", "support", "bonus"] },
    { id: "ray-of-sickness", name: "Ray of Sickness", level: 1, prepared: true, alwaysPrepared: true, actionType: "action", range: "60 ft.", concentration: false, saveOrAttack: "+6 attack", summary: "Poison damage with a chance to poison the target.", tags: ["damage", "poison"] },
    { id: "flaming-sphere", name: "Flaming Sphere", level: 2, prepared: true, alwaysPrepared: true, actionType: "action", range: "60 ft.", concentration: true, saveOrAttack: "Dex save 14", summary: "Area denial and repeatable fire damage.", tags: ["damage", "control", "concentration"] },
    { id: "melfs-acid-arrow", name: "Melf's Acid Arrow", level: 2, prepared: true, alwaysPrepared: true, actionType: "action", range: "90 ft.", concentration: false, saveOrAttack: "+6 attack", summary: "Reliable acid damage over two rounds.", tags: ["damage", "acid"] },
    { id: "faerie-fire", name: "Faerie Fire", level: 1, prepared: true, actionType: "action", range: "60 ft.", concentration: true, saveOrAttack: "Dex save 14", summary: "Outline targets to grant advantage and reveal invisibility.", tags: ["control", "support", "concentration"] },
    { id: "snare", name: "Snare", level: 1, prepared: false, actionType: "action", range: "Touch", concentration: false, saveOrAttack: "Dex save 14", summary: "Magical trap for exploration or ambush setups.", tags: ["utility", "control"] },
    { id: "tashas-caustic-brew", name: "Tasha's Caustic Brew", level: 1, prepared: true, actionType: "action", range: "Self (30 ft. line)", concentration: true, saveOrAttack: "Dex save 14", summary: "Line of acid that pressures enemies to spend actions.", tags: ["damage", "acid", "control", "concentration"] },
    { id: "false-life", name: "False Life", level: 1, prepared: false, actionType: "action", range: "Self", concentration: false, saveOrAttack: "Temp HP", summary: "Gain temporary hit points before danger.", tags: ["defense", "support"] },
    { id: "grease", name: "Grease", level: 1, prepared: true, actionType: "action", range: "60 ft.", concentration: false, saveOrAttack: "Dex save 14", summary: "Creates difficult positioning and prone pressure.", tags: ["control"] },
    { id: "identify", name: "Identify", level: 1, prepared: false, actionType: "utility", range: "Touch", concentration: false, saveOrAttack: "Ritual", summary: "Reveal item or magic properties.", tags: ["ritual", "utility"] },
    { id: "alarm", name: "Alarm", level: 1, prepared: false, actionType: "utility", range: "30 ft.", concentration: false, saveOrAttack: "Ritual", summary: "Protect a campsite or room.", tags: ["ritual", "utility"] },
    { id: "cure-wounds", name: "Cure Wounds", level: 1, prepared: false, actionType: "action", range: "Touch", concentration: false, saveOrAttack: "Healing", summary: "Strong single-target healing, can be delivered by Veech.", tags: ["healing", "support"] },
    { id: "detect-magic", name: "Detect Magic", level: 1, prepared: false, actionType: "utility", range: "Self", concentration: true, saveOrAttack: "Ritual", summary: "Sense nearby magic while exploring.", tags: ["ritual", "utility", "concentration"] },
    { id: "disguise-self", name: "Disguise Self", level: 1, prepared: false, actionType: "action", range: "Self", concentration: false, saveOrAttack: "Utility", summary: "Short-term social infiltration tool.", tags: ["utility"] },
    { id: "expeditious-retreat", name: "Expeditious Retreat", level: 1, prepared: false, actionType: "bonus", range: "Self", concentration: true, saveOrAttack: "Utility", summary: "Dash every turn for repositioning.", tags: ["mobility", "bonus", "concentration"] },
    { id: "feather-fall", name: "Feather Fall", level: 1, prepared: true, actionType: "reaction", range: "60 ft.", concentration: false, saveOrAttack: "Reaction", summary: "Emergency fall protection for the party.", tags: ["reaction", "escape"] },
    { id: "jump", name: "Jump", level: 1, prepared: false, actionType: "action", range: "Touch", concentration: false, saveOrAttack: "Utility", summary: "Triple jump distance for a minute.", tags: ["mobility"] },
    { id: "longstrider", name: "Longstrider", level: 1, prepared: true, actionType: "action", range: "Touch", concentration: false, saveOrAttack: "Utility", summary: "Increase speed by 10 feet for 1 hour.", tags: ["mobility", "support"] },
    { id: "purify-food-and-drink", name: "Purify Food and Drink", level: 1, prepared: false, actionType: "action", range: "10 ft.", concentration: false, saveOrAttack: "Utility", summary: "Makes suspicious provisions safe.", tags: ["utility"] },
    { id: "sanctuary", name: "Sanctuary", level: 1, prepared: true, actionType: "bonus", range: "30 ft.", concentration: false, saveOrAttack: "Wis save 14", summary: "Protect a vulnerable ally without concentration.", tags: ["support", "bonus", "escape"] },
    { id: "absorb-elements", name: "Absorb Elements", level: 1, prepared: true, actionType: "reaction", range: "Self", concentration: false, saveOrAttack: "Reaction", summary: "Resistance now, extra elemental damage later.", tags: ["reaction", "defense"] },
    { id: "catapult", name: "Catapult", level: 1, prepared: false, actionType: "action", range: "60 ft.", concentration: false, saveOrAttack: "Dex save 14", summary: "Launch an object into a target for bludgeoning damage.", tags: ["damage", "utility"] },
    { id: "aid", name: "Aid", level: 2, prepared: true, actionType: "action", range: "30 ft.", concentration: false, saveOrAttack: "Support", summary: "Raise max HP for Brek and allies.", tags: ["support", "healing"] },
    { id: "alter-self", name: "Alter Self", level: 2, prepared: false, actionType: "action", range: "Self", concentration: true, saveOrAttack: "Utility", summary: "Adaptive utility or disguise through transformation.", tags: ["utility", "concentration"] },
    { id: "arcane-lock", name: "Arcane Lock", level: 2, prepared: false, actionType: "action", range: "Touch", concentration: false, saveOrAttack: "Utility", summary: "Seal doors or containers against intrusion.", tags: ["utility"] },
    { id: "blur", name: "Blur", level: 2, prepared: false, actionType: "action", range: "Self", concentration: true, saveOrAttack: "Defense", summary: "Attacks against Brek have disadvantage.", tags: ["defense", "concentration"] },
    { id: "continual-flame", name: "Continual Flame", level: 2, prepared: false, actionType: "action", range: "Touch", concentration: false, saveOrAttack: "Utility", summary: "Permanent flame for utility or story use.", tags: ["utility"] },
    { id: "darkvision", name: "Darkvision", level: 2, prepared: false, actionType: "action", range: "Touch", concentration: false, saveOrAttack: "Utility", summary: "Grant 60-foot darkvision for 8 hours.", tags: ["utility"] },
    { id: "enhance-ability", name: "Enhance Ability", level: 2, prepared: true, actionType: "action", range: "Touch", concentration: true, saveOrAttack: "Support", summary: "Advantage and rider benefits for a chosen ability.", tags: ["support", "concentration", "utility"] },
    { id: "enlarge-reduce", name: "Enlarge/Reduce", level: 2, prepared: false, actionType: "action", range: "30 ft.", concentration: true, saveOrAttack: "Con save 14", summary: "Flexible combat and exploration size change.", tags: ["control", "support", "concentration"] },
    { id: "heat-metal", name: "Heat Metal", level: 2, prepared: true, actionType: "action", range: "60 ft.", concentration: true, saveOrAttack: "Con save 14", summary: "Reliable damage and control against armored foes.", tags: ["damage", "control", "concentration"] },
    { id: "invisibility", name: "Invisibility", level: 2, prepared: true, actionType: "action", range: "Touch", concentration: true, saveOrAttack: "Utility", summary: "Stealth, escape, or infiltration tool.", tags: ["escape", "utility", "concentration"] },
    { id: "lesser-restoration", name: "Lesser Restoration", level: 2, prepared: true, actionType: "action", range: "Touch", concentration: false, saveOrAttack: "Support", summary: "End blindness, deafness, paralysis, or poison.", tags: ["support", "healing"] },
    { id: "levitate", name: "Levitate", level: 2, prepared: false, actionType: "action", range: "60 ft.", concentration: true, saveOrAttack: "Con save 14", summary: "Control an enemy or solve vertical problems.", tags: ["control", "utility", "concentration"] },
    { id: "magic-mouth", name: "Magic Mouth", level: 2, prepared: false, actionType: "action", range: "30 ft.", concentration: false, saveOrAttack: "Utility", summary: "Leave a magical message or warning.", tags: ["utility"] },
    { id: "magic-weapon", name: "Magic Weapon", level: 2, prepared: false, actionType: "bonus", range: "Touch", concentration: true, saveOrAttack: "Support", summary: "Buff a weapon for a harder fight.", tags: ["support", "bonus", "concentration"] },
    { id: "protection-from-poison", name: "Protection from Poison", level: 2, prepared: false, actionType: "action", range: "Touch", concentration: false, saveOrAttack: "Support", summary: "Neutralize poison and grant resistance.", tags: ["support"] },
    { id: "rope-trick", name: "Rope Trick", level: 2, prepared: false, actionType: "action", range: "Touch", concentration: false, saveOrAttack: "Utility", summary: "Create a short rest hideaway.", tags: ["escape", "utility"] },
    { id: "see-invisibility", name: "See Invisibility", level: 2, prepared: false, actionType: "action", range: "Self", concentration: false, saveOrAttack: "Utility", summary: "Spot invisible creatures and objects.", tags: ["utility"] },
    { id: "spider-climb", name: "Spider Climb", level: 2, prepared: false, actionType: "action", range: "Touch", concentration: true, saveOrAttack: "Utility", summary: "Move along walls or ceilings.", tags: ["mobility", "concentration"] },
    { id: "web", name: "Web", level: 2, prepared: true, actionType: "action", range: "60 ft.", concentration: true, saveOrAttack: "Dex save 14", summary: "Strong battlefield control and restraint pressure.", tags: ["control", "concentration"] },
    { id: "pyrotechnics", name: "Pyrotechnics", level: 2, prepared: false, actionType: "action", range: "60 ft.", concentration: false, saveOrAttack: "Con save 14", summary: "Create fireworks or smoke from an existing flame.", tags: ["control", "utility"] },
    { id: "skywrite", name: "Skywrite", level: 2, prepared: false, actionType: "utility", range: "Sight", concentration: true, saveOrAttack: "Ritual", summary: "Write a message in the sky.", tags: ["ritual", "utility", "concentration"] },
    { id: "tortoise-shell", name: "Tortoise Shell", level: 2, prepared: false, actionType: "action", range: "Self", concentration: true, saveOrAttack: "Defense", summary: "Strong defensive shell at the cost of mobility.", tags: ["defense", "concentration"] },
  ],
  elixirs: [
    { id: "elixir-swift-1", name: "Potion of Swiftness", effect: "+10 ft. walking speed for 1 hour", holder: "Brek", consumed: false, duration: "1 hour" },
    { id: "elixir-swift-2", name: "Potion of Swiftness", effect: "+10 ft. walking speed for 1 hour", holder: "Pack", consumed: false, duration: "1 hour" },
    { id: "elixir-flight-1", name: "Potion of Flight", effect: "Fly speed 10 ft. for 10 minutes", holder: "Brek", consumed: false, duration: "10 minutes" },
    { id: "elixir-flight-2", name: "Potion of Flight", effect: "Fly speed 10 ft. for 10 minutes", holder: "Pack", consumed: false, duration: "10 minutes" },
  ],
  features: [
    { id: "action-cast", name: "Cast an action spell", category: "action", trigger: "On Brek's turn", effect: "Use an action spell from the prepared list." },
    { id: "action-extra-elixir", name: "Create Experimental Elixir", category: "action", trigger: "On Brek's turn", effect: "Spend a spell slot to create another elixir." },
    { id: "action-veech", name: "Command Veech", category: "action", trigger: "On Brek's turn", effect: "Command Veech to take an action other than Dodge." },
    { id: "bonus-hide", name: "Nimble Escape: Hide", category: "bonus", trigger: "On Brek's turn", effect: "Bonus action Hide." },
    { id: "bonus-disengage", name: "Nimble Escape: Disengage", category: "bonus", trigger: "On Brek's turn", effect: "Bonus action Disengage." },
    { id: "bonus-healing-word", name: "Healing Word", category: "bonus", trigger: "Ally is down or needs pickup healing", effect: "Spend a 1st- or 2nd-level slot for emergency healing.", resourceId: "slot1", range: "60 ft." },
    { id: "bonus-command", name: "Command Veech", category: "bonus", trigger: "Need Force Strike, Help, or scouting", effect: "Spend the bonus action so Veech does more than Dodge." },
    { id: "react-flash", name: "Flash of Genius", category: "reaction", trigger: "Ability check or saving throw within 30 ft.", effect: "Add +3 to the roll.", resourceId: "flash", range: "30 ft." },
    { id: "react-lucky", name: "Lucky", category: "reaction", trigger: "Before the outcome is known", effect: "Roll another d20 and choose which result counts.", resourceId: "lucky" },
    { id: "react-absorb", name: "Absorb Elements", category: "reaction", trigger: "Take acid, cold, fire, lightning, or thunder damage", effect: "Gain resistance now and add extra elemental damage on your next melee attack." },
    { id: "react-feather", name: "Feather Fall", category: "reaction", trigger: "Creature within 60 ft. falls", effect: "Reduce falling speed for up to five creatures.", range: "60 ft." },
    { id: "react-shield", name: "Repulsion Shield", category: "reaction", trigger: "Creature hits with a melee attack", effect: "Push the attacker up to 15 feet away.", resourceId: "shield" },
    { id: "passive-savant", name: "Alchemical Savant", category: "passive", trigger: "Eligible healing or acid/fire/necrotic/poison damage roll", effect: "Add +3 to one roll when using alchemist's supplies as the focus." },
    { id: "passive-fury", name: "Fury of the Small", category: "passive", trigger: "Damage a creature larger than Brek", effect: "Add +3 damage once per turn.", resourceId: "fury" },
    { id: "passive-fey", name: "Fey Ancestry", category: "passive", trigger: "Charm effects", effect: "Advantage on saves and can end charmed effects more easily." },
    { id: "passive-darkvision", name: "Darkvision", category: "passive", trigger: "Dim light or darkness", effect: "See in darkness out to 60 feet." },
    { id: "passive-tools", name: "Tool Expertise", category: "passive", trigger: "Any proficient tool check", effect: "Double proficiency bonus." },
  ],
  tools: [
    { id: "alchemist", name: "Alchemist's Supplies", uses: "Chemicals, poisons, alchemical identification, potion-like solutions", suggestedAbility: "Intelligence", modifier: "+9" },
    { id: "jeweler", name: "Jeweler's Tools", uses: "Gems, appraisal, delicate craftwork", suggestedAbility: "Intelligence", modifier: "+9" },
    { id: "smith", name: "Smith's Tools", uses: "Metalwork, repairs, forged objects", suggestedAbility: "Strength or Intelligence", modifier: "+5 / +9" },
    { id: "thieves", name: "Thieves' Tools", uses: "Locks, traps, bypassing mechanisms", suggestedAbility: "Dexterity", modifier: "+8" },
    { id: "tinker", name: "Tinker's Tools", uses: "Repairs, mechanisms, improvised devices", suggestedAbility: "Intelligence", modifier: "+9" },
  ],
  infusionsKnown: [
    { id: "known-weapon", name: "Enhanced Weapon", itemType: "Simple or martial weapon", attunement: "No", summary: "Bonus to attack and damage rolls." },
    { id: "known-shot", name: "Repeating Shot", itemType: "Simple or martial weapon with ammunition", attunement: "No", summary: "Magical ammo, ignores loading, and grants a bonus to attack and damage." },
    { id: "known-focus", name: "Enhanced Arcane Focus", itemType: "Rod, staff, or wand", attunement: "No", summary: "Bonus to spell attack rolls and ignore half cover." },
    { id: "known-defense", name: "Enhanced Defense", itemType: "Armor or shield", attunement: "No", summary: "Bonus to AC while worn or wielded." },
    { id: "known-ring", name: "Spell-Refueling Ring", itemType: "Ring", attunement: "Yes", summary: "Recover an expended spell slot of 3rd level or lower at dawn." },
    { id: "known-shield", name: "Repulsion Shield", itemType: "Shield", attunement: "Yes", summary: "Reaction to push an attacker, limited charges per dawn." },
  ],
  infusionsActive: [
    { id: "active-shield", infusionName: "Repulsion Shield", itemName: "Shield", carrier: "Brek", attunedBy: "Brek", currentCharges: 4, maxCharges: 4, resetType: "dawn", notes: "Reaction push available.", active: true },
    { id: "active-ring", infusionName: "Spell-Refueling Ring", itemName: "Ring", carrier: "Brek", attunedBy: "Brek", currentCharges: 1, maxCharges: 1, resetType: "dawn", active: true },
    { id: "active-defense", infusionName: "Enhanced Defense", itemName: "Studded Leather", carrier: "Brek", attunedBy: "None", currentCharges: 0, maxCharges: 0, resetType: "none", active: true },
  ],
  inventory: [
    { id: "equipped", name: "Equipped", items: ["Blood Spear", "Studded Leather", "Light Crossbow", "Crossbow Bolts", "Dagger", "Darts"] },
    { id: "consumables", name: "Consumables", items: ["Potion of Swiftness x2", "Potion of Flight x2", "Rations", "Torches"] },
    { id: "gear", name: "Adventuring gear", items: ["Alchemist's Supplies", "Thieves' Tools", "Backpack", "Bedroll", "Fine Clothes", "Hemp Rope", "Tinderbox", "Waterskin", "Glass Bottles"] },
    { id: "craft", name: "Crafting materials", items: ["Frosty Staff", "Dire Wolf Teeth", "Vampire Fangs", "Vrock Fang", "Humanoid Teeth"] },
    { id: "quest", name: "Quest items", items: ["Locket with dead sister's name", "My Own Skull"] },
    { id: "misc", name: "Miscellaneous", items: [] },
  ],
  companion: {
    name: "Veech",
    creatureType: "Tiny construct",
    ac: 13,
    maxHp: 11,
    currentHp: 11,
    speed: "20 ft.",
    flySpeed: "30 ft.",
    forceStrike: "+6 to hit, 1d4 + 3 force damage, 30 ft.",
    notes: [
      "Evasion",
      "Channel Magic delivers Brek's touch spell within 120 feet",
      "Acts immediately after Brek",
      "Defaults to Dodge unless commanded",
      "Mending restores 2d6 HP",
    ],
  },
  restChecklist: [
    { id: "prepared-spells", label: "Choose prepared spells", checked: false },
    { id: "reset-slots", label: "Reset spell slots", checked: false },
    { id: "reset-flash", label: "Reset Flash of Genius", checked: false },
    { id: "reset-lucky", label: "Reset Lucky", checked: false },
    { id: "reset-fury", label: "Reset Fury of the Small", checked: false },
    { id: "create-elixirs", label: "Create two Experimental Elixirs", checked: false },
    { id: "replace-infusions", label: "Create, move, or replace infusions", checked: false },
    { id: "confirm-infusions", label: "Confirm active infused items", checked: false },
    { id: "veech-hp-check", label: "Check Veech HP", checked: false },
    { id: "review-inventory", label: "Review inventory and consumables", checked: false },
    { id: "story-effects", label: "Note current quest items / story effects", checked: false },
    { id: "session-note", label: "Add an optional session note", checked: false },
  ],
  eventLog: [
    { id: "seed-1", timestamp: now(), text: "Brek's Field Kit initialized with seeded character data.", sessionLabel: "Session Zero" },
  ],
  currentSessionLabel: "Session Zero",
  notes: "Functional field journal for the current campaign state.",
  ui: {
    activeView: "dashboard",
    spellFilter: "Prepared",
  },
});
